export const ROUTES = {
  HOME: '/',
  FEED: '/feed',
  MY_CLAIMS: '/me',
  LOGIN: '/login',
  REGISTER: '/register',
  GROUPS: '/groups',
  GROUP: '/groups/:id',
  MY_PROFILE: '/profile/me',
  PROFILE: '/profile/:id',
  PLANNER: '/planner',
  TIMER: '/timer',
  ADMIN: '/admin',
  SEARCH: '/search',
  FRIENDS: '/friends',
  CHALLENGES: '/challenges',
  CHALLENGE_DETAIL: '/challenges/:id',
  LEADERBOARD: '/leaderboard',
  SETTINGS: '/settings',
  NOT_FOUND: '*',
} as const
